cloudfoundry/prometheus-boshrelease

src/cloudfoundry_dashboards/cf_router.json

Takes advantage of https://github.com/cloudfoundry-community/firehose_exporter/pull/9 to display router jobs nicely (as /0, /1, etc). Unfortunately this removes history from the graphs because old entries do not match.

use bosh_job_index instead of bosh_index

---

src/cloudfoundry_dashboards/cf_apps_metrics.json

Currently if you have an app with the same name in different orgs or spaces you'll get information about all of them. This patch fixes that.

and org_id and space_id to the queries

---

src/cloudfoundry_dashboards/cf_ router_memory.json
src/cloudfoundry_dashboards/cf_cloud_controller.json
src/cloudfoundry_dashboards/cf_diego_auctions.json

I added a few new dashboards for router memory, diego auctions and cloud controller requests.

adding cf dashboards

---

jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf

In some environments access to ports such as 3000 and 9090 is restricted. Therefore it is useful for nginx to listen on the standard ports (80/443) and to use the server_name to differentiate between grafana, prometheus and alertmanager. The defaults remain the same.

make server_name configurable

---

jobs/alertmanager/spec
jobs/alertmanager/templates/bin/alertmanager_ctl

When sitting behind a `proxy` the `alertmanager` is not able to ping `slack` or whatever outside service. This PR allows to set a `http_proxy` setting which will configure `http_proxy` and `https_proxy` for the `alertmanager`.

Allow setting of HTTP and HTTPS proxy vars

---

src/bosh_alerts/bosh_jobs.alerts
src/bosh_alerts/bosh_processes.alerts

We have Cloud Foundry deployed across 2 data centres. Each data centre deployment is managed by a separate bosh instance. Job names, job indexes and AZs are the same in both data centres, hence the need to differentiate by bosh exporter.
This change should not break anything for a single bosh exporter scenario.

Multiple bosh exporters differentiation: include "instance" field in bosh alert definitions

---

jobs/prometheus/spec
jobs/prometheus/templates/config/prometheus.yml

This allows operators to configure [remote storage](https://prometheus.io/docs/operating/configuration/#<remote_write>). If set, samples will
be sent to a remote endpoint.

Add remote_write property to prometheus job

---

jobs/grafana/spec
jobs/grafana/templates/config/grafana.ini

So that users don't accidentally use the default of admin / admin.

Require operators to set non-default admin password.

---

jobs/grafana/spec
jobs/grafana/templates/bin/prometheus-dashboards

So that we can use something like
```yaml
properties:
grafana:
prometheus:
dashboard_files:
- /var/vcap/packages/bosh_dashboards/*.json
```
instead of listing all dashboard files manually.

Accept glob patterns in grafana dashboard files.

---

jobs/grafana/templates/bin/prometheus-dashboards
src/cloudfoundry_dashboards/cf_organization_memory_quotas.json

A bug was introduced with the glob patterns support that caused this script not to process any dashboards with errors like this:
ls: cannot access /var/vcap/packages/cloudfoundry_dashboards/*.json: No such file or directory
It works for me after removing quotes.

fix the prometheus-dashboards script

---

jobs/kubernetes_alerts/spec
packages/kubernetes_alerts/packaging
packages/kubernetes_alerts/spec
src/kubernetes_alerts/pods.alerts

So that operators can be alerted when k8s pods are stuck in a pending or error state.
cc @linuxbozo @cnelson

Add k8s pod status alert.

---

jobs/nginx/templates/config/alertmanager_location.conf
jobs/nginx/templates/config/grafana_location.conf
jobs/nginx/templates/config/prometheus_location.conf

This strips the path from the url before forwarding to the upstream. From the nginx docs:
> If proxy_pass is specified without a URI, the request URI is passed to the server in the same form as sent by a client when the original request is processed, or the full normalized request URI is passed when processing the changed URI

Include path in proxy_pass directive.

---

src/cloudfoundry_dashboards/cf_cells_capacity.json

I added `bosh_job_name` filter to cf_cells_capacity dashboard
In production environments, each cell has different computing resources or need to calculate resources for specific cell groups
For example case, when deployed colocated cell per projects or limited resource environment
It will be useful to calculate capacity for each cell or groups of cells

Add bosh_job_name filter to cf_cells_capacity

---

jobs/grafana/spec
jobs/grafana/templates/bin/prometheus-dashboards

- Allows operator to specify a custom homepage for the default org in
the deployment manifest
- The manifest property should be a JSON string in the following format:
http://docs.grafana.org/reference/dashboard/

Add `grafana.dashboards.custom_homepage_json` bosh property

---

jobs/bosh_alerts/spec
jobs/bosh_alerts/templates/bosh_deployments.alerts

For compliance and security purposes, we want to be alerted when deployments are using an outdated stemcell. We're planning to update this property via concourse using a `bosh-io-stemcell` resource.
cc @cnelson

Optionally alert on outdated stemcells.

---

jobs/elasticsearch_dashboards/spec
jobs/elasticsearch_dashboards/templates/elasticsearch.json

Lightly modified from https://grafana.com/dashboards/2322.
Note: some of these dashboards won't work until we upgrade to the latest `elasticsearch_exporter`. Any reason not to upgrade to 0.3.1? I see that upstream hasn't published binaries for that version, so we might need to build our own.

Add elasticsearch dashboard.

---

jobs/elasticsearch_alerts/spec
jobs/elasticsearch_alerts/templates/cluster.alerts

Adapted from https://grafana.com/dashboards/2322. Note: the elastic exporter emits green as 0, yellow as 1, and red as 2: https://github.com/justwatchcom/elasticsearch_exporter/blob/master/exporter.go#L568-L578.
I made the alert on yellow optional, since elastic clusters might be yellow for a long time during a rolling restart.
cc @cnelson @LinuxBozo

Add elasticsearch alerts.

---

jobs/concourse_alerts/spec
jobs/concourse_alerts/templates/concourse.alerts

* I don't personally plan to alert on goroutes, mallocs, etc., so I didn't include those. I'd be happy to add more alerts if others would find them useful.
* Metrics like `http-response-time` won't work with the influx exporter, since concourse sends a metric for each request, and the exporter doesn't seem to know how to aggregate them. I'm guessing concourse would need to emit aggregates for these metrics to be useful here. Or we could propose some form of configurable aggregate for the influx exporter, or even fork it to add concourse-specific behavior.
* At the moment, concourse metrics from the influx exporter aren't namespaced at all, which is why the metric referenced here is `worker_containers` and not something more explicit like `concourse_worker_containers`. I suggested …

Add minimal concourse alerts.

---

manifests/prometheus.yml

These changes: https://github.com/cloudfoundry-community/prometheus-boshrelease/commit/5048a64cf1ab2a1f5b03b62befef603a6219ee78
Also require the latest version of the release.

Use release 17.6.1 in manifest

---

jobs/alertmanager/spec
jobs/prometheus/templates/bin/prometheus_ctl

If you have to use a route prefix for the alertmanager, prometheus has to know about it.

Adding route prefix to the alertmanager url

---

jobs/elasticsearch_alerts/spec
jobs/elasticsearch_alerts/templates/cluster.alerts
jobs/elasticsearch_dashboards/templates/elasticsearch.json

The elasticsearch exporter refactored and renamed alerts recently. This patch updates alerts for release https://github.com/justwatchcom/elasticsearch_exporter/releases/tag/v1.0.1. We'll also need to update the elasticsearch dashboard and package the new release. I'll take a look at the dashboard later this week; @frodenas, could you add the new release when you get a chance?

Bump alerts for latest elasticsearch exporter.

---

jobs/grafana/spec
jobs/grafana/templates/bin/prometheus-datasource

In some network configurations it's advantageous to have grafana communicate directly with prometheus even when prometheus has been configured with `web.external_url`.
This PR adds a flag to allow this which defaults to preserving the existing behaivor of using the external url when one is provided.
cc: @jmcarp

Allow grafana to use prometheus_ip even when external_url is provided

---

manifests/operators/monitor-bosh.yml

mysql job auto discovery regex contained mondogdb_exported instead of mysqld_exporter.

mysqld_exporter for mysql job instead of mongo_exporter

---

jobs/grafana/spec
jobs/grafana/templates/bin/influxdb-datasource
jobs/grafana/templates/bin/post-start

Related to: https://github.com/cloudfoundry-community/prometheus-boshrelease/pull/118
This PR adds automatic creation of influxdb datasource in Grafana if grafana.influxdb.* properties are set. It currently doesn't support BOSH links  - this can be added in the future but currently no InfluxDB bosh releases provide links anyway.

Automatically create influxdb datasource

---

jobs/elasticsearch_dashboards/templates/elasticsearch.json

Elasticsearch dashboard templating is not working because since justwatchcom/elasticsearch_exporter#65 the elasticsearch_up metric is in the elasticsearch_cluster_health namespace.
This fixes commit e2925b2.

Fix Elasticsearch dashboard templating

---

manifests/operators/monitor-bosh.yml

As recommended by
https://github.com/prometheus/pushgateway#about-the-job-and-instance-labels.

Honor scraped labels when scraping push gateway.

---

jobs/bosh_alerts/templates/bosh_system_predict.alerts
jobs/bosh_alerts/templates/bosh_tsdb_system_predict.alerts

When using Pivotal Cloud Foundry we get false alarms due to BOSHJobEphemeralDiskPredictWillFill alerts on short-lived errand VMs running CF smoke tests.
We've tested this by creating the alerts manually in the prometheus UI and asserting that the alerts are not triggered

Ignore smoke-test VMs when predicting ephemeral disk will fill

---

jobs/alertmanager/templates/bin/alertmanager_test

The test alert is missing a name. I hardcoded it to "TestAlert". If necessary I can add a new variable to allow customization.

Give the test alert a name

---

manifests/operators/prometheus-web-external-url.yml

The primary reason for adding this is to make the "source" link on alerts in Alert Manager take you to the web accessible URL for prometheus.   
By default it tries to take you to a URL with the BOSH instance-group id of the prometheus node which isn't too helpful.

an operator file to allow setting the external URL value for prometheus.

---

jobs/elasticsearch_alerts/templates/cluster.alerts

ElasticHeapUsage alert tries to reference the "name" label, without accessing the "labels" maps. This lead to this message:
```
msg="Error expanding alert template ElasticHeapUsage with data '{map[cluster:logsearch
instance:logsearch bosh:bosh job:logsearch area:heap host:192.168.0.1 name:elasticsearch_data/0] 0.93169611788588
56}': runtime error: invalid memory address or nil pointer dereference" source="alerting.go:200"
```

Fix Elasticsearch alerts

---

jobs/prometheus/templates/bin/prometheus_ctl

When you have a lot of metrics, Prometheus stopping process can take longer than the 25s default wait time of utils.sh. After this timeout, Prometheus is killed with a SIGKILL and when restarted it has to recover. This can take a looong time...
I increased the stop wait timeout to 60s in order to allow big Prometheus installation to shut down properly. If necessary, I can add a new variable to allow tuning of this timeout.

Increase Prometheus stop wait timeout

---

jobs/bosh_alerts/templates/bosh_jobs.alerts
jobs/bosh_alerts/templates/bosh_processes.alerts
jobs/bosh_alerts/templates/bosh_system.alerts
jobs/bosh_alerts/templates/bosh_system_predict.alerts
jobs/bosh_alerts/templates/bosh_tsdb_jobs.alerts
jobs/bosh_alerts/templates/bosh_tsdb_system.alerts
jobs/bosh_alerts/templates/bosh_tsdb_system_predict.alerts

Recently released PCF Healthwatch tile includes a BOSH Director smoke test which deploys a new VM every 10 minutes. This triggers alerts as this VM is considered unhealthy. Currently the name of the deployment, bosh-health-check, is hardcoded so it's easy to exclude it. If it becomes configurable in the future we may need to change this into a regexp configurable in the manifest.

do not alert on bosh-health-check deployment

---

jobs/cloudfoundry_alerts/templates/cf_diego.alerts

Use `firehose_counter_event_auctioneer_auctioneer_lrp_auctions_failed_total` for `CFLRPAuctionsFailedTooHigh` alert.
cc @jmcarp

Use lrp_failed_auction metric for lrp failed auction alert

---

jobs/nginx/templates/config/grafana_location.conf

Grafana seems to ignore path information in root_url for it's own internal router. Using an URL path hence breaks Grafana. Nginx has to remove the path, see also Grafana documentation at https://github.com/grafana/grafana/blob/master/docs/sources/installation/behind_proxy.md .

make nginx remove url path for grafana

---

jobs/cloudfoundry_alerts/templates/cf_cells.alerts

This allows you to deploy multiple cell clusters as bosh jobs and have per cluster alerts.
In case you have multiple cell clusters that are severely unbalanced, current aggregation will miss some potentially problematic situations. Typical case is when you use isolation segments to isolate some workloads.
For example, with alert `CFCellsOverallAvailableMemoryTooLow`, with two almost full clusters and a third empty cluster, chances are that the overall average usage is below the threshold so you'll miss the alerts for the first two clusters.

Add bosh_job_name to aggregation for cells alerts

---

jobs/cloudfoundry_alerts/spec
jobs/cloudfoundry_alerts/templates/cf_apps.alerts

As discussed with Ferdy and Ramon this change helps us differentiate on alerts for apps or components.

parameterize service name for apps alerting

---

jobs/grafana/templates/bin/grafana-admin-password

netcat (nc command) "-z" option does not exist with RedHat/CentOS distribtions to test TCP port availability. 
Remove "-z" option and provide "/dev/null" as command input. Patch works for both Utuntu and CentOS stemcells.

Patch netcat command to make it compatible with CentOS stemcell

---

jobs/elasticsearch_dashboards/templates/elasticsearch.json

Now shows the correct values for Number of Nodes and Unassigned shards in grafana for elastic search metrics.

Fixes expr for unassigned shards and for node count

---

manifests/operators/cf/add-prometheus-uaa-clients.yml

`cloud_controller.admin_read_only` seems to be safer for cf_exporter.

Make cf_exporter client read only

---

jobs/cloudfoundry_dashboards/templates/cf_apps_requests.json

Request/sec graph was summing the rate for a consolidation window, which led to numbers changing depending on how zoomed in or out the graph was. This should get the avg rate for the window and be more accurate/consistent

Update CF app request rate to avg over timewindows vs sum

---

manifests/operators/alertmanager-slack-receiver.yml

`send_resolved` is `false` by default for only [slack](https://prometheus.io/docs/alerting/configuration/#%3Cslack_config%3E) (and [email](https://prometheus.io/docs/alerting/configuration/#%3Cemail_config%3E) which is missing at this moment)
All users I have ever met are expecting sending resolved.
If changing this default is not preferable, I would make a pr for another ops-file like 
``` yaml
- type: replace
path: /instance_groups/name=alertmanager/jobs/name=alertmanager/properties/alertmanager/receivers/name=default/slack_configs/0/send_resolved?
value: true
```

Set send_resolved=true for prometheus alerting

---

jobs/cloudfoundry_dashboards/templates/cf_doppler_server_v2.json
jobs/cloudfoundry_dashboards/templates/cf_metron_agent_v2.json

Hey,
I added two dashboard to be compatible with the metrics available since loggregator version 101.04 as discussed in #170.
That's what the dashboards look like:

Adding dashboards compatible with loggregator version 101.4

---

jobs/p_rabbitmq_alerts/spec
jobs/p_rabbitmq_alerts/templates/p_rabbitmq.alerts

Adds the `p_rabbitmq_alerts.queue_depth.warning` and `p_rabbitmq_alerts.queue_depth.critical` properties to `p_rabbitmq_alerts` for optional alerts on RabbitMQ queue depth.

Add alarm for queue depth on p_rabbitmq_alerts

---

jobs/kube_state_metrics_exporter/templates/bin/kube_state_metrics_exporter_ctl

As of https://github.com/kubernetes/kube-state-metrics/pull/371, the
`--in-cluster` flag is unsupported. Passing this flag now causes
`kube-state-metrics` to error.

Drop unused `--in-cluster` flag.

---

jobs/cloudfoundry_dashboards/templates/cf_uaa.json

By the way, wdyt about using `rate` for the rest of the uaa dashboards? They're all counters, so that might make the panels more intuitive to look at.

Add UAA latency and error rate to dashboard.

---

manifests/operators/migrations/migrate_from_prometheus_1.yml

The az name in the prometheus v1 migration ops file differs from the default az name used in prometheus.yml. This is just bringing them inline, to reduce the need for extra ops files/cloud config when using the migration instance groups.

Fix az name in the prometheus v1 migration ops file

---

jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf

add client_header_buffers parameters to fix 413 (Request Entity Too Large) error is returned to the client.
get this error with Grafana Request.

nginx_client_header_buffers

---

jobs/cloudfoundry_dashboards/spec
jobs/cloudfoundry_dashboards/templates/cf_component_metrics_v2.json

As metrics collection moves from dropsonde to go-loggregator, a bunch of metrics are being dropped: https://github.com/cloudfoundry/go-loggregator/issues/30. This breaks the `label_values` queries and leads to a bunch of empty panels in the component metrics dashboard. This patch updates the templating queries, grabs the list of services from a query instead of hard-coding, and drop panels for metrics that are being deprecated.

Fix component metrics dashboard.

---

manifests/operators/external-lb-from-cloud-config.yml

If you want an internet-accessible prometheus in your public iaas deployment, it's likely that you'll want to attach a load balancer to the front of it using `vm_extensions`. This PR provides a small opsfile to inject one of those vm extensions to the nginx instance group, as well as some commentary on what you might do to your `cloud-config` to get that working.

add external-lb-from-cloud-config opsfile

---

jobs/cloudfoundry_dashboards/templates/cf_component_metrics_v2.json

This should solve the problem occurred in issue #221 .
Added 'v2' to title and uid of the Components Metrics v2 dashboard. 
Afterwards Grafana was able to load it.

Fixes issue with Grafana not showing Components Metrics v2 dashboard

---

jobs/probe_dashboards/templates/probe_https_summary.json

We were probing a URL that contained a `)`, a `$` and a `.` inside of a GET parameter.
Even when we URL encoded, by the time prometheus was done with it, we noticed the Grafana dashboard failing.
Changing the the `=~` to a `=` seemed to fix it for us.
I'm not a Grafana or Prometheus guru, but as far as I can tell, `=~` is a regex match? If so, surely nearly all the dashboards should be changed to an equality check? ie if you're selecting a target from a drop-down menu wouldn't one normally want exact matches only?
Anyway, in lieu of a bigger PR to do that, here's a little one to fix our issue.
I do worry that blindly substituting a user provided string into another string like this is inherently dangerous, but I suspect that's a bigger Grafana issue (e.g. what if `$target` contains a …

Stop trying to match via regex - as this fails if the target actually contains regex chars

---

jobs/postgres_exporter/spec
jobs/postgres_exporter/templates/bin/postgres_exporter_ctl

Allows the use of dedicated postgres exporters for only generating metrics based on queries

Support Postgres exporter for just custom queries

---

jobs/prometheus2/spec
jobs/prometheus2/templates/bin/prometheus_ctl

While [migrating](https://prometheus.io/docs/prometheus/latest/migration/) from Prometheus v1 to v2, the `staleness-delta` parameter was renamed to `lookback-delta`.
This PR fixes a typo in the new name.

Fix typo in lookback-delta parameter

---

jobs/alertmanager/spec
jobs/alertmanager/templates/config/alertmanager.yml
manifests/operators/proxy/enable-proxy-alertmanager-v1-5-0.yml
manifests/operators/proxy/enable-proxy-alertmanager.yml

Fixes issue #234 .
Adds property to alertmanager spec and config template.
Adds also an ops file to enable the new proxy url.

Enable proxy for Alertmanager v1.5.0

---

jobs/prometheus2/templates/bin/prometheus_ctl

The enable-admin-api was not called the right way so it was not possible to enable it at the moment. The changes should fix this.

Fixes Prometheus --web.enable-admin-api flag

---

manifests/operators/use-sqlite3.yml

The `postgres_grafana_password` password variable doesn't need to exist if the database instance_group has been removed.

Remove `postgres_grafana_password` password variable

---

jobs/consul_alerts/templates/consul.alerts.yml

This PR fixes the alert expression of `ConsulNodeHealthCheckFailing` as described in issue #243

Fix consul_exporter alerts 

---

jobs/concourse_alerts/templates/concourse.alerts.yml

To fix this error in AlertManager
```
<error expanding template: error parsing template __alert_ConcourseHighWorkerContainers: template: __alert_ConcourseHighWorkerContainers:1: undefined variable "$bosh_deployment">
<error expanding template: error parsing template __alert_ConcourseHighWorkerContainers: template: __alert_ConcourseHighWorkerContainers:1: undefined variable "$bosh_deployment">
```
$labels.bosh_deployment and $labels.worker are the corrects for template.

Error expanding template

---

jobs/alertmanager/spec
jobs/alertmanager/templates/bin/alertmanager_ctl

This PR adds two optional spec properties on alertmanager job:
* **cluster.listen_address**: controls `--cluster.listen-address`  (overriding default `spec.ip` if present)
* **cluster.advertise_address**: controls `--advertise-address`
These properties can be helpfull when building alertmanager clusters on [multi homed VMs](https://bosh.io/docs/networks/#multi-homed).

Allow more cluster configuration on alertmanager

---

packages/credhub_exporter/packaging
packages/credhub_exporter/spec

This PR bumps [credhub_exporter](https://github.com/orange-cloudfoundry/credhub_exporter) to version [0.1.5](https://github.com/orange-cloudfoundry/credhub_exporter/releases/tag/v0.1.5) which fixes `SIGSEGV` error reported in #248 
* file `credhub_exporter/credhub_exporter-0.1.4.linux-amd64.tar.gz` can be removed
* file `credhub_exporter/credhub_exporter-0.1.5.linux-amd64.tar.gz` must be added. It can be downloaded  from [https://github.com/orange-cloudfoundry/credhub_exporter/releases/download/v0.1.5/credhub_exporter-0.1.5.linux-amd64.tar.gz](https://github.com/orange-cloudfoundry/credhub_exporter/releases/download/v0.1.5/credhub_exporter-0.1.5.linux-amd64.tar.gz)
Thanks:
* @amuessig for the issue
* @damzog for the fix
* and of course @frodenas for your great work :+1:

Bump credhub_exporter to 0.1.5

---

packages/credhub_exporter/packaging
packages/credhub_exporter/spec

This PR bumps [credhub_exporter](https://github.com/orange-cloudfoundry/credhub_exporter) to version [0.1.6](https://github.com/orange-cloudfoundry/credhub_exporter/releases/tag/v0.1.6) which another program crash
* file `credhub_exporter/credhub_exporter-0.1.5.linux-amd64.tar.gz` can be **removed**
* file `credhub_exporter/credhub_exporter-0.1.6.linux-amd64.tar.gz` must be **added**. It can be downloaded  from [https://github.com/orange-cloudfoundry/credhub_exporter/releases/download/v0.1.6/credhub_exporter-0.1.6.linux-amd64.tar.gz](https://github.com/orange-cloudfoundry/credhub_exporter/releases/download/v0.1.6/credhub_exporter-0.1.6.linux-amd64.tar.gz)
Thanks:
* @jtuchscherer  for the fix

bump credhub_exporter to version 0.1.6

---

manifests/prometheus.yml

Set ubuntu-xenial as default stemcell os type.

Adjust default stemcell to use xenial instead of trusty

---

manifests/operators/enable-grafana-generic-oauth.yml
manifests/operators/enable-root-url.yml

TL;DR:
=====
- Add operator for `generic_oauth` (non-biased OAuth2 configuration)
- Add operator for `root_url` (requisite for OAuth2 redirect)
Detail:
======
These operators allow a deployment to have a generic OAuth2 provider
added as an authentication mechanism for Grafana. This includes all
values that are presented in the [spec](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/grafana/spec#L267-L296).
All variables are configurable, with the exception of the following:
- `grafana.auth.generic_oauth.enabled`
- `grafana.auth.generic_oauth.allow_sign_up`
The `enabled` attribute is our intended purpose of adding this
operator, so that will always be set to `true`. The `allow_sign_up`
attribute provides the ability to allow or deny the creation of users
in …

Add Generic OAuth2 Operator for Grafana

---

jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf

Currently the nginx job will add all Prometheus, Alertmanager and Grafana instances to the upstream configurations. We want to be able to tell nginx that it should only forward requests to instances in the same availability zone.
This PR adds three extra parameters (`*.cross_zone_load_balancing`) with a default true, so it's possible to disable cross-zone load balancing.
We are deploying Prometheus in an HA setup, so we have two independent clusters in two availability zones. We want to disable any cross-zone load balancing so we always know which servers are we communicating with.

Add option to nginx job to disable cross zone load balancing

---

jobs/firehose_exporter/spec
jobs/firehose_exporter/templates/bin/firehose_exporter_ctl

Allow to set a unique subscription id for the firehose-exporter
This PR adds a new parameter called `firehose_exporter.doppler.use_unique_subscription_id`. If it's true then the BOSH VM id will be added as a suffix to the subscription id.
The default value of `firehose_exporter.doppler.subscription_id` will be set to `prometheus` as if this is not set the firehose-exporter will still use that as a default value. This makes it clearer to use it together with the `use_unique_subscription_id` flag.

Allow to set a unique subscription id for the firehose-exporter

---

jobs/cloudfoundry_dashboards/templates/cf_metron_agent_v2.json

Just a small quality of life thing.
The graph for Metron Egress is displaying in bytes, when it looks like it should be just a number of messages.
Swapped the format from bytes to short so it is displayed as a number of messages.
Old: 
New:

Correct the y-axes for the Metron Egress in the CF: Metron Agent dashboard from bytes to short

---

manifests/operators/concourse/enable-prometheus-metrics.yml
manifests/operators/monitor-bosh.yml

Job name for `atc` has been renamed to `web` in concourse 5.0.

Support Concourse 5.0

---

jobs/prometheus2/spec
jobs/prometheus2/templates/bin/prometheus_ctl

This PR will substitute the deprecated `storage.tsdb.retention`property to `storage.tsdb.retention.time` as mentioned in #296 .
I decided to go with the `.time` instead of `_time` to be more flexible to add `storage.tsdb.retention.size` to spec as soon as it leaves status experimental.

Switch from storage.tsdb.retention property to storage.tsdb.retention.time

---

jobs/prometheus2/spec
jobs/prometheus2/templates/config/prometheus.yml
jobs/prometheus2/templates/config/remote_write_ca.crt

1. Add a BOSH link support for remote_write configuration.
1. Allow to consume CA cert for remote_write, useful when remote_write storage configured with HTTPS.

Consume remote_write connection through a BOSH link

---

jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf

Allow setting custom resolver for nginx, and allow toggling IPv6 resolution for that resolver.
Motivation:
Nginx only resolves hostnames once at startup if you don't declare a resolver. This causes issues when one or more of the upstreams nginx is targeting gets a new IP address.

Allow setting resolver for nginx

---

jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf

We have pretty long domain names and Nginx is failing to start with the following error:
```
2019/07/12 12:45:13 [emerg] 30360#0: could not build server_names_hash, you should increase server_names_hash_bucket_size: 64
```
This PR allows to increase `server_names_hash_bucket_size ` config property for Nginx.

Allow setting server_names_hash_bucket_size for Nginx

---

jobs/grafana/spec

`grafana.security`, `grafana.security` so good they named it twice.
It's actually just `grafana.security.cookie_samesite` in [the template](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/e96d2f275e635b5d3c49a6905dc5a6a7f2be03cb/jobs/grafana/templates/config/grafana.ini#L324-L327)

Drop duplicate prefix from cookie_samesite

---

jobs/bosh_alerts/spec
jobs/bosh_alerts/templates/bosh_system.alerts.yml
jobs/bosh_alerts/templates/bosh_tsdb_system.alerts.yml

Closes #312 
Added to property to remove the value-labels for bosh alerts. The new property defaults to false which ensure that the current behavior does not change for anyone but provides the possibility to disables those values if wanted.

Add property to remove {{value}} from alert descriptions

---

jobs/graphite_exporter/templates/bin/graphite_exporter_ctl

In the newest versions for graphite-exporter the option --graphite.mapping-strict-match doesn't accept any passing value, due to this, it is necessary to update the logic in the job's template due to is failing at the moment is being used.

graphite-exporter: changing the variable mapping-strict-match

---

jobs/graphite_exporter/spec
jobs/graphite_exporter/templates/bin/graphite_exporter_ctl
jobs/graphite_exporter/templates/config/graphite_mapping.conf
jobs/graphite_exporter/templates/config/graphite_mapping.yml

Since v0.3.0 graphite_exporter is configured to use YAML style config for metrics mapping configuration.
https://github.com/prometheus/graphite_exporter/releases/tag/v0.3.0

Use YAML style config for graphite_exporter

---

jobs/concourse_dashboards/templates/concourse_overview.json
jobs/concourse_dashboards/templates/concourse_pipelines.json

Fixes to concourse dashboard with concourse 5
- some metrics converted to counters in concourse/concourse@838161c
- job scheduling metric removed in concourse/concourse@f3ca6b3
New panels in concourse overview:
- Started - Finished Builds
- Database locks held
- Top 10 job builds
- Table of all successful jobs executions since last concourse restart
On my integration server, this looks like
@frodenas @jmcarp
I'm still new to prometheus, so dashboard might require fine tuning for syntax changes that I might have overlooked
There are a few over panels that might be useful, possibly in a new dashboard, which I did not include yet in this PR:
- history of build failures
- resource checks per pipeline
In the future, I'd like to find a way to add more concourse internal metrics to match …

Concourse dashboard fixes & refinements

---

jobs/cloudfoundry_dashboards/templates/cf_organization_memory_quotas.json
jobs/cloudfoundry_dashboards/templates/cf_organization_summary.json
jobs/cloudfoundry_dashboards/templates/cf_space_summary.json

* cf_organization_memory_quotas.json: Updating graphs to multiply memory usage by the number of instances and fix the data type to standard instead of decimal megabytes
* cf_organization_summary.json: Updating graphs to only show running instances to correspond with how CF implements quota, updating descriptions, removing extraneous memory quota line on the disk usage chart, and multiply memory and disk usage by the number of instances.
* cf_space_summary.json: Updating graphs to only show running instances to correspond with how CF implements quota, updating descriptio
ns, removing extraneous memory quota line on the disk usage chart, and multiply memory and disk usage by the number of instances.

Updating org and space dashboards with the following changes:

---

jobs/credhub_exporter/templates/bin/credhub_exporter_ctl
jobs/credhub_exporter/templates/config/credhub_tls_ca_cert.pem

Hi,
This PR fixes the names of properties that are accessed through the `credhub` BOSH link.
Indeed, those properties are prefixed with `credhub.`, as shown [here in the `credhub` job spec](https://github.com/pivotal-cf/credhub-release/blob/master/jobs/credhub/spec#L60-L62).
Best,
Benjamin

Fix the Credhub link properties for credhub_exporter

---

jobs/prometheus2/templates/bin/prometheus_ctl

After the upgrade to v26.0.0 I noticed that `web.external-url` flag shows empty string in Prometheus Command-Line Flags page. In my environment all command line flags after the `storage.tsdb.no-lockfile` flag are not initialized during the start. 
This also affects Alertmanager integration with Prometheus.

Add missing backslashes in prometheus_ctl

---

jobs/consul_exporter/templates/bin/consul_exporter_ctl

The consul exporter template wasn't rendering.
```
L Error: Unable to render instance groups for deployment. Errors are:
- Unable to render jobs for instance group 'prometheus'. Errors are:
- Unable to render templates for job 'consul_exporter'. Errors are:
- Error filling in template '(unknown)' (line (unknown): consul_exporter/bin/consul_exporter_ctl:86: syntax error, unexpected end-of-input, expecting end)
```

Add matching %>s to consul ctl

---

jobs/cf_exporter/templates/bin/cf_exporter_ctl

TODO: build and test in our live environments
[In order to prevent credentials passed to `cf_exporter` being visible in the VM's process table](https://github.com/bosh-prometheus/prometheus-boshrelease/issues/353), this swaps  out passing CLI args to `cf_exporter` in favor of leveraging [exporting the equivalent env args](https://github.com/bosh-prometheus/cf_exporter#flags)
This would be the first of a few commits/PRs to update other exporters, e.g. `firehose-exporter`, `bosh-exporter`, etc.
Open questions/comments:
- Should _only_ credentials be swapped out to leverage env vars? E.g., allow for non-credential args to be passed via CLI so they're still visible in `ps aux`? Reason for not doing this is to maintain consistency.
- Is current spacing acceptable? Or should it have no newlines …

cf_exporter: replace CLI args with ENV args

---

ci/settings.yml
config/blobs.yml
jobs/ingestor_dashboards/spec
jobs/ingestor_dashboards/templates/ingestors.json
jobs/ingestor_exporter/monit
jobs/ingestor_exporter/spec
jobs/ingestor_exporter/templates/bpm.yml.erb
manifests/operators/monitor-bosh.yml
manifests/operators/monitor-elasticsearch-ingestors.yml
manifests/operators/monitor-elasticsearch.yml
packages/ingestor_exporter/packaging
packages/ingestor_exporter/spec

This PR aims to do the following:
* Enables Slack Notifications for when new versions of [ingestor_exporter](https://github.com/bosh-prometheus/ingestor_exporter) are available
* Adds new bosh job "ingestor_exporter" - intended to be ran on ingestor VMs as part of Elasticsearch deployments. Exports firehose-to-syslog metrics on default port 9495. Currently using ingestor_exporter v2.2.0.
* Adds new bosh job "ingestor_dashboards". Contains a Grafana JSON dashboard intended to be placed in the "Elasticsearch" folder. The dashboard utilizes metrics exported by the ingestor_exporter.
* Modifies the "monitor-bosh.yml" ops-file to automatically begin scraping ingestor_exporter metrics on port 9495.
* Adds new ops-file "monitor-elasticsearch-ingestors.yml". This adds an ingestor dashboard to …

Monitor Elasticsearch Ingestors

---

jobs/bosh_exporter/templates/bin/bosh_exporter_ctl
jobs/firehose_exporter/templates/bin/firehose_exporter_ctl

Continuation of https://github.com/bosh-prometheus/prometheus-boshrelease/pull/354
@frodenas let me know if you'd like me to update the rest of these exporters; I can do it in a single PR which touches many of these. Or only this PR which update the ones _I_ personally actively use at first? etc. Apologies, just checking before I drop a PR with multiple touchpoints.

Convert exporter credentials to envvars 

---

jobs/grafana/templates/bin/grafana-admin-password

Grafana CLI global options _must_ come before command and command options. Currently we are seeing the following error in `less /var/vcap/sys/log/grafana/post-start.stdout.log`:
```
[Wed Nov 20 14:30:12 UTC 2019] Resetting grafana admin password ...
Waiting for grafana to listen on port 3000 (0/60)
Grafana is ready
Incorrect Usage: flag provided but not defined: -homepath
NAME:
Grafana cli admin reset-admin-password - reset-admin-password <new password>
USAGE:
Grafana cli admin reset-admin-password [arguments...]
```
This is because the `grafana-admin-password` script was passing the `-homepath` and `-config` global options _after_ the `admin reset-admin-password` command, which is not supported. I have verified this fix works by manually updating …

Fix bug in grafana admin password reset script

---

jobs/grafana/spec
jobs/grafana/templates/config/provisioning/datasources/custom.yml

Opsfile example:
```yaml
- type: replace
path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/datasources?/delete
value:
- name: Cloudwatch
orgId: 1
- type: replace
path: /instance_groups/name=grafana/jobs/name=grafana/properties/grafana/datasources?/create
value:
- name: Cloudwatch
type: cloudwatch
orgId: 1
jsonData:
authType: keys
defaultRegion: eu-central-1
secureJsonData:
accessKey: "<my-access-key>"
secretKey: "<my-secret-key>"
```

Allow to provision additional Grafana datasources

---

jobs/credhub_dashboards/spec
jobs/credhub_dashboards/templates/credhub_certs.json
manifests/operators/monitor-credhub.yml

Dashboard has a single table with Expiry date and TTL for Credhub entries with `certificate` type.
Screenshot:

Add Credhub Certs Expiry date dashboard

---

jobs/credhub_dashboards/templates/credhub_certs.json

It's better to see the certificates that will expire first on top.

order CredHub Certificate Expiry Date dashboard ascending by Expiry Date

---

jobs/bosh_tsdb_exporter/templates/bin/bosh_tsdb_exporter_ctl
jobs/credhub_exporter/templates/bin/credhub_exporter_ctl
jobs/redis_exporter/templates/bin/redis_exporter_ctl
jobs/shield_exporter/templates/bin/shield_exporter_ctl

Continuation of https://github.com/bosh-prometheus/prometheus-boshrelease/pull/357
Apologies I've taken a weeks longer than I expected to finish this. 
It turns out there's only a handful more jobs which pass creds via CLI rather than `envvars` or config files-- and most aren't using creds directly at all. I've swapped those out, with the exception of the `mongodb_exporter` which doesn't appear to support passing creds via envvar, so ¯\_(ツ)_/¯ no worries
Please let me know if there's anything you'd like changed, etc.; I've got nice and relaxing time now while over break 👌thanks again

Convert exporter credentials to envvars, round 2

---

jobs/prometheus2/spec
jobs/prometheus2/templates/bin/pre-start.erb
jobs/prometheus2/templates/config/prometheus.yml

For context, on the Bosh team, we are trying to deploy a prometheus in our acceptance environment to try out providing our own metrics. (the bosh-exporter is cool, but very expensive to run, metrics provided directly by Bosh should be much cheaper). The bosh metrics endpoint is secured with mTLS and we need to give certs to the scrape config.
Thanks,
Charles
PR details:
Prometheus wants scrape_config tls_config to use file paths, but it is difficult
to directly put certificates on a vm while deploying with bosh.
If cert_contents are provided, the pre-start script will write the
contents into cert files that prometheus can use when it starts
Prometheus validates that there are not extra keys in its configuration,
so the extra cert contents keys need to be removed. …

Allow cert contents in prometheus scrape config tls config

---

jobs/rabbitmq_exporter/spec

The [rabbitmq_exporter_ctl  template](https://github.com/bosh-prometheus/prometheus-boshrelease/blob/master/jobs/rabbitmq_exporter/templates/bin/rabbitmq_exporter_ctl#L61) expects the property name to be max_queues.

Fix property name for max_queues

---

config/blobs.yml
packages/prometheus2/packaging
packages/prometheus2/spec

In order to leverage more efficient versions of prometheus, this PR bumps from prometheus 2.15.2 to the latest of 2.19.0. The [posted changelogs with releases is listed here](https://github.com/prometheus/prometheus/releases). I have tested this on a corporate-internal environment and haven't experienced problems.
Blobs: if accepted, blobs will need to be stored and uploaded into the blobstore:
```sh
wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
bosh add-blob prometheus-2.19.0.linux-amd64.tar.gz prometheus/prometheus-2.19.0.linux-amd64.tar.gz
bosh remove-blob prometheus/prometheus-2.15.2.linux-amd64.tar.gz
```

prometheus 2.15.2 to 2.19.0

---

jobs/grafana/templates/config/grafana.ini

Property reference in bosh template was missing `f` in `feature`. This is referenced as `grafana.feature_toggles.enable` in the grafana `spec`

Fixup property reference naming for grafana.feature_toggles

---

jobs/grafana/templates/config/provisioning/datasources/influxdb.yml
jobs/grafana/templates/config/provisioning/datasources/prometheus.yml

In order to store datasource passwords encrypted, and to move off the deprecated configuration property formats, the values for `password` and `basicAuthPassword` should be moved under `secureJsonData`
see also:
- https://github.com/grafana/grafana/pull/16175/files/62c1d03b68f50b1f3d10f415c7b3544133865ce3
- https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources

Store grafana datasource credentials using secureJson

---

config/blobs.yml
jobs/grafana/spec
jobs/grafana/templates/config/grafana.ini
packages/grafana/packaging
packages/grafana/spec

In order to leverage grafana 7.x, this PR bumps from grafana 6.5.3 to the latest of 7.0.3. The [posted changelog is listed here](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#70-feature-highlights). I have tested this on a corporate-internal environment which uses CF's UAA for oauth and CF's routing-release for prometheus/alertmanager/grafana route registration, and haven't experienced any full-on failure issues.
for convenience if cross-referencing grafana conf differences, [here's the 7.0.3 defaults.ini](https://github.com/grafana/grafana/blob/v7.0.3/conf/defaults.ini), and the [grafana upgrade guide for all versions up to 7.0.3](https://grafana.com/docs/grafana/latest/installation/upgrading/)
Blobs: if accepted, blobs will need to be stored and uploaded into the …

bump grafana 6.5.3 to 7.0.3

---

manifests/operators/proxy/enable-proxy-alertmanager.yml

Fix http_config option so it appears as a global option in alertmanager.yml.
Previous setup was not working.

fix http_config option to work

---

packages/credhub_exporter/packaging
packages/credhub_exporter/spec

This PR bumps credhub-exporter to [v0.2.2](https://github.com/orange-cloudfoundry/credhub_exporter/releases/tag/v0.2.2)
```
wget https://github.com/orange-cloudfoundry/credhub_exporter/releases/download/v0.2.2/credhub_exporter_0.2.2_linux_amd64.tar.gz
bosh add-blob credhub_exporter_0.2.2_linux_amd64.tar.gz credhub_exporter/credhub_exporter_0.2.2_linux_amd64.tar.gz
bosh remove-blob credhub_exporter/credhub_exporter-0.2.0-linux_amd64-0.2-0.zip
```

bump credhub_exporter to v0.2.2

---

jobs/credhub_alerts/spec

The currently used version of the credhub_exporter uses 6h as the default
scraping interval [1,2]. This commit adjusts the default value of
scrape_too_old for credhub_alerts to 6h, in order to not throw any
alerts for a default deployment.
[1] https://github.com/orange-cloudfoundry/credhub_exporter/blob/v0.2.2/README.md#flags
[2] https://github.com/orange-cloudfoundry/credhub_exporter/blob/v0.2.2/credhub_exporter.go#L65

adjust default value of credhub_alerts.scrape_too_old.threshold

---

manifests/operators/monitor-bosh-director.yml

Adds an ops file to add scrape config for the bosh directors metrics server. 
The server needs to be enabled via the following spec: https://github.com/cloudfoundry/bosh/blob/8b2baa8435342f5eb00d334991eab4addf72a5df/jobs/director/spec#L248 
or if bosh-deployment is used by the use of the following ops file https://github.com/cloudfoundry/bosh-deployment/blob/master/experimental/enable-metrics.yml
Closes  #410 , #399

Add ops file to monitor bosh director metrics

---

manifests/prometheus.yml

Closes #418 
As Bionic Stemcells are GA now, we should switch to use them.

Switch from Xenial to Bionic Stemcells

---

jobs/alertmanager/spec
jobs/alertmanager/templates/bin/alertmanager_ctl
jobs/alertmanager/templates/config/alertmanager.yml
jobs/grafana/spec
jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf
jobs/prometheus2/spec
jobs/prometheus2/templates/bin/prometheus_ctl
jobs/prometheus2/templates/config/prometheus.yml

This PR brings some features that should be helpful for the infrastructure where a fronting proxy (e.g., oauth2-proxy) is deployed together with prometheus, grafana, and alertmanager VMs and have nginx access them. Furthermore, it adds missing features that are currently unsupported by this BOSH release. The bug fixes are included as well.
- `prometheus.web.listen_address`, `alertmanager.web.listen_address`
- The port that Prometheus/Alertmanager listens to. It could be set to `127.0.0.1` so it limits access but from localhost.
- Grafana already has this option.
- `nginx.prometheus.https_redirect_url`, `nginx.grafana.https_redirect_url`, and `nginx.alertmanager.https_redirect_url`
- The redirect URL that nginx returns when redirecting to HTTPS, which is helpful to normalize address like …

Add missing features and fix bugs

---

config/blobs.yml
packages/grafana_plugins/packaging
packages/grafana_plugins/spec

This MR bumps the Grafana plugin `flant-statusmap-panel` from v0.3.4 to v0.4.2.
As per the [Statusmap-panel ChangeLog](https://github.com/flant/grafana-statusmap/blob/master/CHANGELOG.md), the version 0.3 does not work on Grafana 7.5+.
```bash
wget -O flant-statusmap-panel-v0.4.2.zip https://grafana.com/api/plugins/flant-statusmap-panel/versions/0.4.2/download
bosh add-blob flant-statusmap-panel-v0.4.2.zip grafana_plugins/flant-statusmap-panel-v0.4.2.zip
bosh remove-blob grafana_plugins/flant-statusmap-panel-v0.3.4.zip
```

Bump Statusmap to v4.2.0

---

jobs/credhub_exporter/spec
jobs/credhub_exporter/templates/bpm.yml.erb
packages/credhub_exporter/packaging
packages/credhub_exporter/spec

This PR bumps credhub_exporter from `v0.2.0` to `v0.3.0`.
**Changelog**
- credhub_exporter: 
- bump internal golang dependencies
- replaced `github.com/prometheus/common/log` by `github.com/sirupsen/logrus` as log facility
- add `--log.level`, `--log.stream` and `log.json` command line flags
- bosh spec changes
- remove `credhub_exporter.log_format` 
- replaced by `credhub_exporter.log_stream` (default `stderr`)
**Blobs**
```
wget https://github.com/orange-cloudfoundry/credhub_exporter/releases/download/v0.3.0/credhub_exporter_0.3.0_linux_amd64.tar.gz
bosh add-blob credhub_exporter_0.3.0_linux_amd64.tar.gz credhub_exporter/credhub_exporter_0.3.0_linux_amd64.tar.gz
bosh remove-blob credhub_exporter/credhub_exporter_0.2.2_linux_amd64.tar.gz
```

bump credhub_exporter to v0.3.0

---

jobs/kubernetes_alerts/templates/pods.alerts.yml

We've noted that Kubernetes jobs that create pods, which then successfully run to completion, result in this alert firing.
e.g.
```
NAMESPACE               NAME                                        READY   STATUS      RESTARTS   AGE
kube-system             helm-install-traefik-zzzz                   0/1     Completed   0          18h
kube-system             traefik-xxxx-yyyy                           1/1     Running     0          18h
```
This PR treats a pod with status `Completed` as happy.

Stop firing an alert for completed job pods

---

jobs/credhub_alerts/templates/credhub.alerts.yml

The credential aging alert triggers on certificates but this is not so useful since certificates have their own expiration.
Also the CredHubCertificateWillExpire alert already notifies when certificates are about to expire.

Do not check credential aging for certificates

---

jobs/grafana/spec
jobs/grafana/templates/config/grafana.ini

Grafana job has missing properties configurable since Grafana 7.2+ so this PR adds them.
https://grafana.com/docs/grafana/v7.5/auth/generic-oauth/

Add grafana.auth.generic_oauth.{login,name}_attribute_path

---

jobs/alertmanager/spec
jobs/alertmanager/templates/config/alertmanager.yml

Alertmanager added time_intervals to manage muting/activating routes and deprecated the previously added mute_intervals. This PR adds `time_intervals` while leaving `mute_time_intervals` as is.
Compare:
* https://prometheus.io/docs/alerting/0.23/configuration/
* https://prometheus.io/docs/alerting/0.24/configuration/

Add alertmanager.time_intervals

---

packages/cadvisor/packaging

The prometheus bosh-release cannot be compiled since [v27.2.0](https://github.com/bosh-prometheus/prometheus-boshrelease/releases/tag/v27.2.0)
The problem comes from the `cadvistor` package which produces the following compilation error:
```
ask 81260 | 07:56:22 | Compiling packages: cadvisor/77c88de37951a032f07ec208184f47b1349388ce73a16e18c4e9f743384170b0 (00:02:12)
L Error: Action Failed get_task: Task 8e7a8cf4-aef9-4b51-7026-ffe6e3a964d8 result: Compiling package cadvisor: Running packaging script: Running packaging script: Command exited with 1; Stdout: , Stderr: + mkdir -p /var/vcap/packages/cadvisor/common
+ cp -a /var/vcap/data/compile/cadvisor/common/utils.sh /var/vcap/packages/cadvisor/common
+ mkdir -p /var/vcap/packages/cadvisor/bin
+ tar xzvf …
```

fix cadvisor packaging script

---

jobs/grafana/spec
jobs/grafana/templates/config/grafana.ini

This PR adds the `grafana.auth.generic_oauth.id_token_attribute_name` spec property.
This property allows to configure `[auth.generic_oauth] / id_token_attribute_name` described in [grafana's documentation](https://grafana.com/docs/grafana/v8.5/auth/generic-oauth/#login).
Configuring this property can be useful to read login information from `access_token` instead of default `id_token`.

Grafana: id_token_attribute_name configuration in generic oauth

---

jobs/prometheus2/spec
jobs/prometheus2/templates/bin/prometheus_ctl

This PR allows prometheus2 to enable its features. Multiple features can be enabled by passing `--enable-feature` multiple times.
Doc: https://prometheus.io/docs/prometheus/latest/feature_flags/

Add prometheus.enable_features

---

jobs/nginx/monit

Looking at [this issue](https://github.com/bosh-prometheus/prometheus-boshrelease/issues/452), I feel the solution can be fairly easy. `monit` can track file changes and can have `nginx` process react to these changes. Sending a `SIGHUP` signal to the parent `nginx` process is enough for the workers to refresh.
run `touch /etc/hosts` and see that nginx workers get replaced:
```
47130 ?        S<     0:00 nginx: master process nginx -p /var/vcap/sys/tmp/nginx -c /var/vcap/jobs/nginx/config/nginx.conf
47441 ?        S<     0:00  \_ nginx: worker process
47442 ?        S<     0:00  \_ nginx: worker process
....
47130 ?        S<     0:00 nginx: master process nginx -p /var/vcap/sys/tmp/nginx -c /var/vcap/jobs/nginx/config/nginx.conf
47556 ?        S<     0:00  \_ nginx: worker process
47557 …
```

nginx is aware of hosts file changes

---

manifests/operators/enable-cf-route-registrar.yml
manifests/operators/monitor-cf.yml
manifests/operators/monitor-credhub.yml
manifests/prometheus.yml

Since cf_exporter uses bpm now we need to ensure it is really present.

Ensure BPM is available for cf_exporter

---

jobs/prometheus2/spec
jobs/prometheus2/templates/bin/prometheus_ctl

I think the prometheus remote write receiver can currently be enabled using a feature flag, but it's flag is deprecated so thought it might be worth adding support for `--web.enable-remote-write-receiver` - https://prometheus.io/docs/prometheus/latest/feature_flags/#remote-write-receiver

Add property to enable the prometheus built-in remote write receiver

---

jobs/alertmanager/spec
jobs/alertmanager/templates/bin/alertmanager_ctl
manifests/operators/alertmanager-disable-clustering.yml

When only one alertmanager instance is deployed, alertmanager_cluster_messages_queued will rise over time until it hits 4k queue limit resulting in dropping alerts (https://github.com/prometheus/alertmanager/issues/1814). This PR enables operators to disable clustering for alertmanager.

[alertmanager] Add config to disable clustering

---

config/blobs.yml
packages/cf_exporter/packaging
packages/cf_exporter/spec

This PR bump [cf_exporter](https://github.com/bosh-prometheus/cf_exporter/) from `v1.0.0` to [v1.0.1](https://github.com/bosh-prometheus/cf_exporter/releases/tag/v1.0.1), which includes:
- concurrent requests are handled correctly
- (bosh-prometheus/cf_exporter#82)
- connexions to api are correctly closed 
- (bosh-prometheus/cf_exporter#81)
*Note*: new blob has been uploaded

bump cf_exporter from v1.0.0 to v1.0.1

---

config/blobs.yml
packages/cf_exporter/packaging
packages/cf_exporter/spec

bump cf_exporter to [v1.1.0](https://github.com/bosh-prometheus/cf_exporter/releases/tag/v1.1.0), fixes bosh-prometheus/cf_exporter#85

bump cf_exporter to v1.1.0

---

jobs/grafana/templates/bin/pre-start

`pre-start` script runs `chown` against `/var/vcap/store/grafana` which does not exist on new deployments with persistent `/var/vcap/store` mount point.
This small fix makes sure that `/var/vcap/store/grafana` gets created beforehand.

Make sure /var/vcap/store/grafana exists

---

jobs/grafana/spec
jobs/grafana/templates/config/grafana.ini

In recent deployments we found out that Grafana SQLite3 is locking with an error "Database locked, sleeping then retrying". 
Following [an issue raised](https://github.com/grafana/grafana/issues/65115) in Grafana we are introducing a solution we found useful. Seems that enabling WAL (Write-Ahead Logging, https://sqlite.org/wal.html) in `grafana.ini` resolves the problem.
Using this new Grafana spec property called `grafana.database.wal` enables this feature.

Grafana SQLite3 supports WAL

---

VERSIONS.md
config/blobs.yml
packages/cf_exporter/packaging
packages/cf_exporter/spec

bump cf_exporter to v1.2.2
* this version of cf_exporter fixes wrongly renamed label `application_id`

bump cf_exporter to v1.2.2

---

jobs/firehose_exporter/spec
jobs/firehose_exporter/templates/bpm.yml.erb

This PR add the possibility to disable the retrocompatibilty on the firehose exporter.
https://github.com/bosh-prometheus/prometheus-boshrelease/issues/483

add retro_compat.disable property

---

jobs/firehose_exporter/spec
jobs/firehose_exporter/templates/bpm.yml.erb

As describe here : https://github.com/bosh-prometheus/firehose_exporter/blob/master/FAQ.md
the Delta is not exported by default, enable it by using retro_compat.enable_delta command flag.
This PR add the possibility to enable this option.

add retro_compat.enable_delta option

---

jobs/cf_exporter/spec
jobs/cf_exporter/templates/bpm.yml.erb

`cf_exporter` binary allow usage of `--collector.workers` arguments to customize number of workers that'll be used to fetch informations from cf api.

Adds possibility to customize --collector.workers argument's value in cf_exporter job configuration

---

jobs/grafana/spec
jobs/grafana/templates/config/grafana.ini

Adds a possibility to enable insecure email lookup for Grafana (https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#enable-email-lookup) disabled by default for Grafana v10+.

Add insecure email lookup property to Grafana

---

packages/elasticsearch_exporter/packaging
packages/influxdb_exporter/packaging
packages/pushgateway/packaging
packages/redis_exporter/packaging
packages/statsd_exporter/packaging

This pull request updates the packaging scripts for several exporters in the latest version of prometheus-boshrelease. The following changes have been made to ensure consistency between the extracted and copied package versions, preventing errors during the compilation process:
- **elasticsearch_exporter**: Updated to use version **1.8.0** for both extraction and copy commands.
- **influxdb_exporter**: Updated to use version **0.12.0** for both extraction and copy commands.
- **pushgateway**: Updated to use version **1.10.0** for both extraction and copy commands.
- **redis_exporter**: Updated to use version **1.65.0** for both extraction and copy commands.
- **statsd_exporter**: Updated to use version **0.28.0** for both extraction and copy commands.
These changes align the packaging …

fix exporter package versions

---

jobs/alertmanager/spec
jobs/alertmanager/templates/config/alertmanager.yml

- Integrated **Jira receiver configuration** into Alertmanager.
- Cconfiguration options for Jira integration:
- `description`: Configured global section for Jira Alertmanager.
Please check official alertmanager documentation:
https://github.com/prometheus/alertmanager/blob/b5d1a64ad5bb0ff879705714d1e40cea82efbd5c/docs/configuration.md#jira_config

[ES-1330][alertmanager]Adding Jira Integration To AlertManager

---

jobs/bosh_dashboards/templates/bosh_jobs.json

This is the first dashboard to be updated for the React based panels for Issue #508 . The panel has some visual changes on top. I removed the avg_load05 and avg_load15 metrics, as that metric is not available. 
Before:
After: 
I tested the template file proposed by importing it into another grafana without issues.

[#508][bosh_jobs][dashboard] Migrate to react based dashboards and change layout

---

jobs/bosh_dashboards/templates/bosh_overview.json

Another Bosh Dashboard for #508 . The bosh overview dashboard is a variant of Bosh Jobs. It had several metrics as well that were not emitted by prometheus. While the old did not show errors yet the automigrate migrated them nevertheless to a new type. 
Old:
New 
Tested by importing the template to another grafana and comparing the dashboards there.

[#508][Dashboard] Update bosh-overview dashboard

---

jobs/grafana/templates/bin/pre-start
jobs/grafana/templates/config/grafana.ini

Grafana plugins can be installed in the UI only if the plugin directory (defined in `grafana.ini`) is writable for `vcap` user. Currently the plugin directory is set to `/var/vcap/packages/grafana_plugins` which is writable by root only and not persistent. 
This change moves that directory to the persistent disk `/var/vcap/store` (so that plugins are not lost when the instance is recreated or upgraded) and links all existing plugins from `grafana_plugins` package to that directory.

Enable Grafana plugins installation

---

jobs/bosh_dashboards/templates/bosh_processes.json

Disclaimer: 
We do not currently use this dashboard, and therefore have no data in it. It exports and imports successfully, but I could not verify the line coloration etc, but as the others using the same Graph types went fine I assume it will upgrade like the other, though I would prefer if someone could double check that uses the bosh exporter.
Part of #508

ES1367 update bosh-processes dashboard

---

jobs/cloudfoundry_dashboards/templates/cf_apps_system.json

This is the first dashboard where automatic migration did a mistake. It set the Opacity to 100% on the Average disk/memory allocation graphs. I set those to 10% opacity (as the other panels)
Belongs to #508

ES-1367 Update cf_apps_system Dashboard
