jobs/bosh_exporter/templates/bin/bosh_exporter_ctl

Added UAA parameters to bosh_exporter_ctl (to allow setting them through a manifest)

add UAA parameters to bosh_exporter_ctl

---

src/cloudfoundry_alerts/diego.alerts

You can find context here: https://github.com/cloudfoundry-community/prometheus-boshrelease/issues/24 .
This PR intends to fix this issue.

Fix alerting for diego low remaining memory

---

src/bosh_alerts/bosh_system.alerts

Prometheus creates a lot of files and I ran out of inodes when I had a small disk for Prometheus.

add persistent disk inodes alert

---

jobs/bosh_tsdb_exporter/spec
jobs/bosh_tsdb_exporter/templates/bin/bosh_tsdb_exporter_ctl

This PR attempts to fix basic auth for bosh-tsdb-exporter

Fix bosh-tsdb-exporter auth password

---

manifests/operators/prometheus-bosh-exporter.yml
manifests/operators/prometheus-cf-exporter.yml

This is a followup PR for https://github.com/cloudfoundry-community/prometheus-boshrelease/pull/71 (I was still testing..)
I found 2 small issues. Which are fixed in this PR.

Manifest fixes

---

.gitmodules
jobs/influxdb_exporter/monit
jobs/influxdb_exporter/spec
jobs/influxdb_exporter/templates/bin/influxdb_exporter_ctl
packages/influxdb_exporter/packaging
packages/influxdb_exporter/spec

This exporter is useful to monitor Concourse (recently Concourse added an option to emit metrics to influxdb and this exporter can pretend to be influxdb to gather the metrics)

Add influxdb_exporter

---

jobs/elasticsearch_alerts/templates/cluster.alerts

Fix comparison operators in elasticsearch alerts.

---

jobs/concourse_dashboards/templates/concourse.json

Sorry, I was too sloppy writing this earlier--I actually tested this with `prometheus-dashboards` this time 😓

Fix concourse dashboard layout and templating.

---

jobs/kubernetes_alerts/spec
jobs/kubernetes_alerts/templates/nodes.alerts

Add kubernetes memory and cpu request alerts.

---

jobs/prometheus/spec
jobs/prometheus/templates/config/custom.rules
jobs/prometheus/templates/config/prometheus.yml

Allow custom prometheus alerts from manifest.

---

README.md
manifests/operators/use-sqlite3.yml

It would be nice to have an option of sqlite3 instead of postgres as previous releases.

Add use-sqlite3.yml

---

jobs/prometheus/templates/bin/prometheus_ctl

Credit to @maddi for finding this.

Fix copy and paste error

---

ci/settings.yml

I've already applied this to CI :thumbsup:

only need to check github-release occasionally; save on API limit per hour

---

manifests/operators/alertmanager-victorops-receiver.yml

Victorops requires routing_key now.

Victorops requires routing_key

---

manifests/operators/use-sqlite3.yml

postgres release is unnecessary

Remove postgres release when sqlite3 is used

---

ci/scripts/testflight
manifests/prometheus.yml

This allows you not to have to update your cloud-config just to use this
manifest.

Use ints for persistent_disk_type

---

jobs/concourse_alerts/templates/concourse.alerts
jobs/concourse_dashboards/templates/concourse.json
manifests/operators/monitor-bosh.yml
manifests/operators/monitor-cadvisor.yml
manifests/operators/monitor-concourse.yml

We should look into adding more views to the dashboard now that the built-in concourse exporter exists and is shipping more metrics.

[WIP] Scrape built-in concourse exporter.

---

.final_builds/packages/golang-1.9-linux/index.yml
config/blobs.yml
packages/golang-1.9-linux/spec.lock
packages/golang_prometheus/packaging
packages/golang_prometheus/spec
packages/kube_state_metrics_exporter/packaging
packages/kube_state_metrics_exporter/spec

So that I don't have to compile as many golang packages.

Vendor golang package.

---

jobs/cloudfoundry_alerts/spec
jobs/cloudfoundry_alerts/templates/cf_diego.alerts

Adds basic alerts on grootfs errors. It might also be useful to alert on other metrics from grootfs, and to add some dashboards, eventually.
cc @wjwoodson

Add basic grootfs alerts.

---

jobs/nginx/spec
jobs/nginx/templates/config/nginx.conf

So that operators can set custom headers for each service in nginx.

Allow custom headers in nginx config.

---

jobs/p_rabbitmq_alerts/templates/p_rabbitmq.alerts.yml

Signed-off-by: David Bishop <dbisj@allstate.com>

Corrects typo for expr

---

jobs/prometheus2/templates/config/prometheus.yml

Fix alertmanager route_prefix configuration in Prometheus config

---

jobs/vault_alerts/templates/vault.alerts.yml

Update expr for vault.alerts.yml

---

jobs/prometheus2/spec
jobs/prometheus2/templates/bin/prometheus_ctl

Add retention size parameter for prometheus

---

jobs/cloudfoundry_alerts/templates/cf_cells.alerts.yml
jobs/cloudfoundry_dashboards/templates/cf_cell_summary.json
jobs/cloudfoundry_dashboards/templates/cf_diego_health.json
jobs/cloudfoundry_dashboards/templates/cf_kpis.json

UnhealthyCell metric deprecated in favor of GardenHealthCheckFailed

---

jobs/concourse_dashboards/templates/concourse_overview.json
jobs/concourse_dashboards/templates/concourse_pipelines.json

Updating concourse url
Signed-off-by: Max Knee <Max_Knee@comcast.com>

Update concourse url

---

manifests/operators/use-sqlite3.yml

This PR remove operation for missing property.
Could you please review and merge it?
Related commit: https://github.com/bosh-prometheus/prometheus-boshrelease/commit/699de42d276007d4a4267ec3a86d697b3e591e19

Remove operation in use-sqlite3.yml

---

jobs/cloudfoundry_dashboards/templates/cf_doppler_server_v2.json
jobs/cloudfoundry_dashboards/templates/cf_metron_agent_v2.json

Updated some of the queries to allow multiple firehose exporter instances.

Update queries to allow multiple firehose exporter instances

---

jobs/elasticsearch_exporter/spec
jobs/elasticsearch_exporter/templates/bin/elasticsearch_exporter_ctl

`es.indices_mappings` - introduced in ES Exporter v1.2.0

Support for es.indices_mappings

---

jobs/grafana/templates/bin/grafana-homepage

This PR fixes #449 
I took the opportunity to refactor the script in order to be more explicit in case of errors.

grafana: fix home dashboard

---

.github/workflows/stale-issue-pr.yml

This PR adds a workflow to manage stalled issues and PR.

Add stale issue and pr workflow

---

README.md
VERSIONS.md

This PR adds a documentation page showing all available components of the release, their version and the latest upstream available version.

Add status of available components in readme

---

jobs/mysqld_exporter/spec
jobs/mysqld_exporter/templates/bin/mysqld_exporter_ctl

See associated metrics at https://github.com/prometheus/mysqld_exporter/blob/2ef168bf68f326cf0f87973a215f9c52163f9bda/collector/info_schema_schemastats.go#L35-L52

Add support for mysqld_exporter.collect.info_schema.schemastats

---

jobs/cloudfoundry_dashboards/templates/cf_apps_latency.json

Update of the apps latency dashboard. As the underlying Data source is broken, see: https://github.com/cloudfoundry/firehose_exporter/issues/87 no data is shown.
belongs to #508

Update cf_apps_latency dashboard
